output_dir: ~/scratch/torchglycan_output/

dataset:
  class: GlycanPretrain
  path: ~/scratch/glycan-datasets/
  view: glycan
  unit_feature: default
  link_feature: default

task:
  class: GlycanAttributeMasking
  mask_rate: 0.3
  num_mlp_layer: 2
  model:
    class: GlycanRGCN
    num_unit: 143
    num_relation: 84
    input_dim: 128
    hidden_dims: [128, 128, 128]
    concat_hidden: True
    readout: dual

optimizer:
  class: Adam
  lr: 5.0e-4
  weight_decay: 0.001

engine:
  gpus: {{ gpus }}
  batch_size: 256

train:
  num_epoch: 50

save_path: path/to/ckpt/
