output_dir: ~/scratch/torchglycan_output/

dataset:
  class: GlycanClassification
  path: ~/scratch/glycan-datasets/
  target_fields: ["class"]
  view: atom-glycan
  unit_feature: default
  link_feature: default
  atom_feature: symbol
  bond_feature: symbol

task:
  class: GlycanPropertyPrediction
  model:
    class: GlycanAA
    num_unit: 210
    num_relation: 89
    input_dim: 128
    hidden_dims: [128, 128, 128]
    concat_hidden: True
    batch_norm: True
    activation: gelu
    readout: dual
  criterion: ce
  metric: ["acc", "mcc", "macrof1"]
  num_mlp_layer: 2
  num_class: 1737

metric: macrof1 [class]

optimizer:
  class: Adam
  lr: 5.0e-4
  weight_decay: 0.001

engine:
  gpus: {{ gpus }}
  batch_size: 256

train:
  num_epoch: 50
  
scheduler:
  class: CosineAnnealingLR
  T_max: 100
