output_dir: ~/scratch/torchglycan_output/

dataset:
  class: GlycanClassification
  path: ~/scratch/glycan-datasets/
  target_fields: ["species"]
  view: glycan
  unit_feature: default
  link_feature: default

task:
  class: GlycanPropertyPrediction
  model:
    class: GlycanGearNet
    num_unit: 143
    num_relation: 84
    input_dim: 128
    hidden_dims: [128, 128, 128]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
  criterion: ce
  metric: ["acc", "mcc", "macrof1"]
  num_mlp_layer: 2
  num_class: 1737

metric: macrof1 [species]

optimizer:
  class: Adam
  lr: 5.0e-4
  weight_decay: 0.001

engine:
  gpus: {{ gpus }}
  batch_size: 64

train:
  num_epoch: 50

scheduler:
  class: CosineAnnealingLR
  T_max: 100
